name: Release PR verification
on:
  pull_request:
    branches:
      - main
  
jobs:
  check-release-branch-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check source branch prefix
        run: |
          if [[ "${{ github.head_ref }}" != release/* ]]; then
            echo "PR must come from a branch starting with release/"
            exit 1
          fi
      - name: Fetch tags
        run: git fetch --tags
      - name: Check for matching tag
        run: |
          echo "Get the latest commit for the PR branch"
          git fetch origin ${{ github.head_ref }}
          COMMIT=$(git rev-parse origin/${{ github.head_ref }})
          echo "last commit is: $COMMIT"
          echo "Finding tags for this commit"
          # Getting all tags from commit
          TAGS=$(git tag --points-at $COMMIT)
          # Checking if there any tags attached to commit
          if [[ -z "$TAGS" ]]; then
            echo "Tags are missing"
            exit 1
          fi
          
          VTAG=$(grep -E '^(v|release)' <<< "$TAGS")
          if [[ -z "$VTAG" ]]; then
            echo "v** or release** tag is missing. Add correct tag into commit"
            exit 1
          fi
          
          echo "Release commit with tag $VTAG"