on:
  pull_request:
    branches:
      - main
  
jobs:
  check-release-branch-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check source branch prefix
        run: |
          if [[ "${{ github.head_ref }}" != release/* ]]; then
            echo "PR must come from a branch starting with release/"
            exit 1
          fi
      - name: Fetch tags
        run: git fetch --tags
      - name: Check for matching tag
        run: |
          echo "Get the latest commit for the PR branch"
          git fetch origin ${{ github.head_ref }}
          COMMIT=$(git rev-parse origin/${{ github.head_ref }})
          echo "last commit is: $COMMIT"
          echo "Finding tags for this commit"
          TAGS=$(git tag --points-at $COMMIT | grep -E '^(v|release)')
          echo "lets check if there is any tag TAGS = $TAGS"
          if [[ -z "$TAGS" ]]; then
            echo "No matching tag (v* or release*) found on the PR branch commit"
            exit 1
          else
            echo "Commit $COMMIT has following tag: $TAGS"
          fi
